return PlaceObj('ModDef', {
	'title', "Wardrobe",
	'description', "[h1]Wardrobe[/h1]\n\n[h3]The main goal of this mod is to provide more entities such as clothes, vehicles, items, etc to be used as assets by other modders.[/h3]\n\n[i]There is an appearance preset in the mod that you can use to try tweak the position of the entities. You can tweak some values to make hats, belts, bags, etc, fit in the appearance you want. Also, in case you don't know, you can manually attach bags and other items to the female mesh. [b]I don't know why the editor don't index them to the female hip and chest as to male.[/b Another sidenote,[b] YOU CAN ATTACH ANY EQUIPMENT TO ANY POINT OF COLLISION MANUALLY[/b]\n\n[i]List of collision points, limited by creature type, humans usually don't have tails.[/i]\n\n[list]\n	[*]\"Head\"\n	[*]\"Neck\"\n	[*]\"Torso\"\n	[*]\"Groin\"\n	[*]\"Shoulderl\"\n	[*]\"Shoulderr\"\n	[*]\"Elbowl\"\n	[*]\"Elbowr\"\n	[*]\"Wristl\"\n	[*]\"Wristr\"\n	[*]\"Pelvisl\"\n	[*]\"Pelvisr\"\n	[*]\"Kneel\"\n	[*]\"Kneer\"\n	[*]\"Ribsupperl\"\n	[*]\"Ribsupperr\"\n	[*]\"Ribslowerl\"\n	[*]\"Ribslowerr\"\n	[*]\"Tail\"\n[/list]",
	'image', "Mod/Wardrobe/Images/OIG3 (1).jpg",
	'external_links', {
		"https://github.com/yasumitsu/Wardrobe",
	},
	'last_changes', "- description jokes",
	'id', "Wardrobe",
	'author', "Sir Ni",
	'version', 88,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'entities', {
		"FemaleEntTop",
		"FemaleEntHead",
		"HGBasicPantsGrey",
		"HGSuitGrey",
		"FemaleSortOfShirt",
		"FemaleSkirt",
		"FemaleEntBottom",
		"FemaleEntTop1",
		"HatFemale",
		"TutAirplane",
		"RedPlane",
		"KombiDoBope",
		"lwachoppera",
		"WoodenClub",
	},
	'code', {
		"Entities/FemaleEntTop.lua",
		"Entities/FemaleEntHead.lua",
		"Entities/HGBasicPantsGrey.lua",
		"Entities/HGSuitGrey.lua",
		"Entities/FemaleSortOfShirt.lua",
		"Entities/FemaleSkirt.lua",
		"Entities/FemaleEntBottom.lua",
		"Entities/FemaleEntTop1.lua",
		"Entities/HatFemale.lua",
		"Entities/TutAirplane.lua",
		"Entities/RedPlane.lua",
		"Entities/KombiDoBope.lua",
		"Entities/lwachoppera.lua",
		"Entities/WoodenClub.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1720691790,
	'code_hash', 6173550375833641139,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Boobs",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "DummyFemaleTest",
			'ClassDisplayName', "Appearance preset",
		}),
	},
	'steam_id', "3257716618",
	'TagLibs&ModdingTools', true,
})